'use strict';
// Report companion only. No implementation, fixture, or baseline is changed.
// Usage: node <this file> <source-root> <output.json>
// The arithmetic oracle below does not call model tax/rule helpers or load RULES.
const fs = require('node:fs'), path = require('node:path');
const root = path.resolve(process.argv[2] || '.'), output = process.argv[3];
const L = require(path.join(root, 'audit/S5AA/R40/S5AA_R40_CONSERVATION_GRID/lib.js'));
const E = L.h.engine, V = L.h.validateScenario, a = L.account;
const b = o => L.basePlan({ dividendOn: true, dividendYield: 0, ...o });
const cases = []; let c;
function check(label, actual, expected, tolerance = .01) {
  const passed = typeof expected === 'number' ? Number.isFinite(actual) && Math.abs(actual - expected) <= tolerance : JSON.stringify(actual) === JSON.stringify(expected);
  c.checks.push({ label, actual, expected, tolerance, passed });
}
function test(id, name, fn) { c = { id, name, checks: [], executions: [] }; try { fn(); } catch (e) { c.error = e.stack; } c.pass = !c.error && c.checks.every(x => x.passed); cases.push(c); }
function run(p) { const v = V(structuredClone(p)), r = E.runPlan(structuredClone(p)); c.executions.push({ plan: p, validator: v, result: r }); check('validator valid', v.valid, true); check('engine status', r.status, 'ok'); return r; }
const final = r => r.rows.at(-1);
const stream = (amount, end = 66, owner = 'self') => ({ id: 'job', name: 'Job', type: 'employment', owner, amount, start: 65, end, growth: 0, growthMode: 'fixed' });
const caps = { single: [12400,50400,105700,201775,256225,640600,Infinity], mfj: [24800,100800,211400,403550,512450,768700,Infinity], hoh: [17700,67450,105700,201750,256200,640600,Infinity] };
const rates = [.1,.12,.22,.24,.32,.35,.37];
const standard = { single:16100,mfj:32200,hoh:24150 }, cg0 = { single:49450,mfj:98900,hoh:66200 }, cg15 = { single:545500,mfj:613700,hoh:579600 };
function ordinaryTax(x, f) { let n = Math.max(0,x), out = 0, lo = 0; for(let i = 0;i < caps[f].length;i++) { const width = Math.min(n, caps[f][i]-lo); out += width*rates[i]; n -= width; lo = caps[f][i]; if(n <= 0) break; } return out; }
function ssTax(ss, other, f) { const base=f==='mfj'?32000:25000, upper=f==='mfj'?44000:34000, pi=other+ss/2; return pi<=base?0:pi<=upper?Math.min(ss/2,(pi-base)/2):Math.min(.85*ss,Math.min(ss/2,(upper-base)/2)+.85*(pi-upper)); }
// 2026 resident-AZ model scope, nonnegative gains, no SE/QBI/prior-year offset.
// Federal amounts: Rev. Proc. 2025-32; SS taxation: IRC 86; NIIT: IRC 1411;
// payroll: IRC 3101 / SSA 2026 base. AZ: the declared 2026 parameter assumption.
function tax({ ordinary=0, gains=0, qd=0, ss=0, wages=0, spouseWages=0, filing='single', seniorCount=0 }) {
  const st=ssTax(ss,ordinary+gains+qd,filing), agi=ordinary+gains+qd+st;
  const senior=seniorCount*Math.max(0,6000-.06*Math.max(0,agi-(filing==='mfj'?150000:75000)));
  const deduction=standard[filing]+seniorCount*(filing==='mfj'?1650:2050)+senior;
  const ot=Math.max(0,ordinary+st-deduction), pref=Math.max(0,gains+qd-Math.max(0,deduction-ordinary-st));
  const zero=Math.min(pref,Math.max(0,cg0[filing]-ot)), fifteen=Math.min(pref-zero,Math.max(0,cg15[filing]-Math.max(ot,cg0[filing])));
  const federal=Math.min(ordinaryTax(ot,filing)+fifteen*.15+(pref-zero-fifteen)*.2,ordinaryTax(ot+pref,filing));
  const niit=.038*Math.min(gains+qd,Math.max(0,agi-(filing==='mfj'?250000:200000)));
  const payroll=.062*(Math.min(184500,wages-spouseWages)+Math.min(184500,spouseWages))+.0145*wages+.009*Math.max(0,wages-(filing==='mfj'?250000:200000));
  const az=.025*Math.max(0,ordinary+gains+qd-standard[filing]-2100*seniorCount-senior);
  return { federal,niit,payroll,az,total:federal+niit+payroll+az,agi,ssTaxable:st };
}
function gracePlan(amount, end=66, spouse=false) {
  const p=b({ age:65,spouseAge:65,couple:spouse,retireAge:65.5,endAge:66,salary:spouse?0:50000,spouseSalary:spouse?50000:0,spending:0,ssBenefit:spouse?0:2000,spouseSS:spouse?2000:0,accounts:[a('r','rothIRA',100000)] });
  p.profile.rothFirstContributionYear=2000; p.retirement.ssCola=0;
  if(spouse) { p.profile.spouseRetireAge=65.5;p.retirement.spouseClaim=65.5; } else p.retirement.ssClaim=65.5;
  p.retirement.otherIncomes=[stream(amount,end,spouse?'spouse':'self')]; return p;
}
test('F01','SS grace: employment stream ends before claim',()=> { const p=gracePlan(20000,65.5),r=run(p);check('six monthly checks, $1,800 each',final(r).income-35000,10800); });
test('F02','SS grace: continuing $1,000 monthly wages',()=> { const p=gracePlan(12000),r=run(p),t=tax({ordinary:37000,ss:10800,wages:37000,seniorCount:1}),base=tax({ordinary:25000,wages:25000,seniorCount:1});check('six monthly checks, $1,800 each',final(r).income-37000,10800);check('settled tax',final(r).taxSettled,t.total);check('closing portfolio after incremental tax',final(r).total,100000+22800-(t.total-base.total)); });
test('F03','SS grace: spouse wage stream',()=> { const r=run(gracePlan(12000,66,true));check('spouse six monthly checks',final(r).income-37000,10800); });
test('F04','SS grace: wages above monthly exempt amount',()=> { const r=run(gracePlan(30000));check('no eligible grace months',final(r).income-55000,0); });
test('F05','SS grace: zero stream control',()=> { const r=run(gracePlan(0));check('six monthly checks',final(r).income-25000,10800); });
test('F06','Compound growth with no cash flows',()=> { const r=run(b({age:40,retireAge:70,endAge:50,spending:0,returnRate:7,accounts:[a('r','rothIRA',100000)]}));check('ten-year value',final(r).total,100000*1.07**10); });
test('F07','Fractional final period compounds once',()=> { const r=run(b({age:40,retireAge:70,endAge:42.25,spending:0,returnRate:7,accounts:[a('r','rothIRA',100000)]}));check('fractional horizon',final(r).age,42.25);check('2.25-year value',final(r).total,100000*1.07**2.25); });
test('F08','Fixed nominal spending from qualified Roth',()=> { const r=run(b({age:65,endAge:70,spending:10000,accounts:[a('r','rothIRA',100000)]}));check('five-year spending',r.rows.slice(1).reduce((s,x)=>s+x.spending,0),50000);check('closing balance',final(r).total,50000); });
test('F09','Fixed real spending and real portfolio units',()=> { const p=b({age:65,endAge:70,strategy:'fixedReal',inflation:3,accounts:[a('r','rothIRA',200000)]});p.retirement.withdrawalRate=5;const r=run(p),spent=10000*(1.03**5-1)/.03;check('inflated total spending',r.rows.slice(1).reduce((s,x)=>s+x.spending,0),spent);check('real closing value',final(r).realTotal,(200000-spent)/1.03**5); });
test('F10','Percentage spending uses opening portfolio',()=> { const p=b({age:65,endAge:70,spending:0,strategy:'constantPercent',accounts:[a('r','rothIRA',100000)]});p.retirement.withdrawalRate=10;const r=run(p);check('geometric depletion',final(r).total,100000*.9**5); });
test('F11','Traditional IRA tax funding at deduction and bracket boundaries',()=> { let worst=0,n=0; for(const spend of [0,100,24000,24150,25000,30000,50000,100000,200000,400000]) { const p=b({age:65,endAge:66,spending:spend,accounts:[a('t','traditionalIRA',2000000)]}),r=run(p);let lo=spend,hi=spend*2+1000;for(let i=0;i<100;i++){const x=(lo+hi)/2; if(x-tax({ordinary:x,seniorCount:1}).total<spend)lo=x;else hi=x;}const expected=(lo+hi)/2;worst=Math.max(worst,Math.abs(final(r).withdrawals-expected));n++; }c.summary={plans:n,worstDollarError:worst};check('independent bisection versus funded gross',worst,0); });
test('F12','HSA qualified and nonqualified cash',()=> { for(const share of [0,50,100]) {const p=b({age:60,endAge:61,spending:10000,accounts:[a('h','hsa',100000,{qualifiedMedicalPct:share})]});const r=run(p);const gross=10000/(1-.2*(1-share/100));check('gross with nonqualified 20% tax at low ordinary income '+share,final(r).withdrawals,gross); } });
test('F13','RMD/QCD consumes a distribution without phantom retained cash',()=> { const p=b({age:73,endAge:74,spending:0,rmdOn:true,accounts:[a('t','traditionalIRA',255000)]});p.advanced.qcd=10000;const r=run(p);check('declared opening-age 73 RMD',final(r).rmd,255000/26.5);check('QCD distribution',final(r).rmdDistributed,10000);check('tax-free QCD',final(r).taxSettled,0);check('portfolio paid charity',final(r).total,245000); });
test('F14','Live fixed-rate debt against annuity closed form',()=> { for(const apr of [0,.001,6,20]) { const d={id:'d',type:'loan',balance:10000,rate:apr,paymentMonthly:400,extraPrincipalMonthly:0,payoffAge:80,includePayment:true};const r=E.projectDebts([d],60,61,1,1),i=apr/1200,expected=i===0?5200:10000*(1+i)**12-400*((1+i)**12-1)/i;check('balance APR '+apr,d.balance,expected);check('cash APR '+apr,r.totalPayments,4800);check('principal identity APR '+apr,r.totalPrincipal,10000-expected); } });
test('F15','Debt payoff inside period splits working and retired cash',()=> { const d={id:'d',type:'loan',balance:12000,rate:0,paymentMonthly:1000,payoffAge:60.5,includePayment:true};const r=E.projectDebts([d],60,61,.5,1);check('paid principal',r.totalPayments,12000);check('retired balloon at payoff boundary',r.retirementPayments,6000);check('closing debt',d.balance,0); });
test('F16','Credit card monthly minimum and floor',()=> { const d={id:'d',type:'creditCard',balance:2000,rate:24,paymentMonthly:0,minimumPercentOfBalance:2,minimumDollarFloor:25,payoffAge:90,includePayment:true};const r=E.projectDebts([d],60,61,1,1);check('interest-only minimum',d.balance,2000);check('12 minimum payments',r.totalPayments,480);check('no principal invented',r.totalPrincipal,0); });
test('F17','Live ARM reset reamortizes remaining term',()=> { const d={id:'d',type:'mortgage',balance:12000,rate:0,paymentMonthly:1000,rateType:'adjustable',nextRateResetAge:60.5,resetRate:12,payoffAge:61,includePayment:true};const r=E.projectDebts([d],60,61,1,1);const pay=6000*.01/(1-1.01**-6);check('reset payment',d._armScheduledPayment,pay);check('annual cash',r.totalPayments,6000+6*pay);check('final debt',d.balance,0); });
test('F18','Fallback asset is accessible only after entered date',()=> { const p=b({age:65,endAge:66,spending:10000,networthOn:true,fallback:true,accounts:[a('r','rothIRA',0)],otherAssets:[{id:'x',name:'Cash',value:10000,growth:0,available:true,accessPct:100,availableAge:65.5,liquidity:'liquid'}]});const r=run(p);check('half-year accessible budget',final(r).nonPortfolioDraw,5000);check('remaining unmet spending',final(r).shortfall,5000);check('remaining other asset',final(r).otherAssets,5000); });
test('F19','Zero-volatility Monte Carlo matches closed form',()=> { const p=b({age:40,retireAge:70,endAge:45,spending:0,returnRate:5,accounts:[a('r','rothIRA',100000)]});Object.assign(p.assumptions,{method:'monteCarlo',runs:100,seed:20261004});const r=run(p);for(const k of ['total','q10','q90'])check(k,final(r)[k],100000*1.05**5);check('100% success',r.successRate,100); });
test('F20','Seed reproducibility and input immutability',()=> { const p=b({age:40,retireAge:70,endAge:50,spending:0,accounts:[a('r','rothIRA',100000)]});Object.assign(p.assumptions,{method:'monteCarlo',runs:200,seed:20261004,returnRate:5,volatility:15});p.advanced.assetsOn=false;const before=JSON.stringify(p),one=run(p),two=run(p);check('same seed rows',two.rows,one.rows);check('same seed success',two.successRate,one.successRate);check('input unchanged',JSON.stringify(p),before);p.assumptions.seed++;const three=run(p);check('different seed changes quantiles',three.rows.at(-1).q10!==one.rows.at(-1).q10,true); });
test('F21','Historical return replay arithmetic from specified data years',()=> { const p=b({age:40,retireAge:70,endAge:42,spending:0,accounts:[a('r','rothIRA',100000)]});p.assumptions.method='historical';p.assumptions.historyStart=2020;p.advanced.assetsOn=false;const r=run(p); // Independent multiplication of the declared equity-proxy observations, not an independent market-data qualification.
  check('2020/21 proxy-return compound',final(r).total,100000*1.1802*1.2847); });
test('F22','One-time expense inside and on fractional end boundary',()=> { const p=b({age:65,endAge:66.25,spending:0,accounts:[a('r','rothIRA',100000)],expenses:[{id:'e',name:'Expense',age:66.2,amount:12345}]});const r=run(p);check('interior event counted once',r.rows.reduce((s,x)=>s+x.spending,0),12345);check('event reduces cash once',final(r).total,87655);p.retirement.expenses[0].age=66.25;const q=run(p);check('end boundary excluded',final(q).total,100000);check('end boundary warned',q.issues.some(x=>x.code==='EXPENSE_AFTER_PLAN_END'),true); });
test('F23','Working contribution and compensation caps',()=> { const p=b({age:40,retireAge:45,endAge:41,salary:5000,spending:0,accounts:[a('t','traditionalIRA',0,{contribution:7500}),a('cash','taxable',0)]});const r=run(p);check('IRA limited by compensation',final(r).preTax,5000);check('excess redirected',final(r).taxable,2500); });
test('F24','Taxable zero-basis sale funding by independent oracle',()=> { const p=b({age:65,endAge:66,spending:100000,accounts:[a('t','taxable',500000,{basisPct:0})]});const r=run(p);let lo=100000,hi=200000;for(let i=0;i<100;i++){const x=(lo+hi)/2;if(x-tax({gains:x,seniorCount:1}).total<100000)lo=x;else hi=x;}check('gross taxable sale',final(r).withdrawals,(lo+hi)/2); });
test('F25','Tax oracle matrix across income, gains, SS and age thresholds',()=> { const income=[0,10000,16100,32200,50000,75000,100000,150000,200000,250000,500000,1000000],gains=[0,10000,50000,200000],benefits=[0,24000,60000];let n=0,worst=0;const failures=[];for(const filing of ['single','mfj','hoh'])for(const age of [60,65])for(const ordinary of income)for(const gain of gains)for(const ss of benefits){const p=b({age,spouseAge:age,couple:filing==='mfj',endAge:age+1,spending:0});p.profile.filing=filing;const s=filing==='mfj'?ordinary/2:0,x=tax({ordinary,gains:gain,ss,wages:ordinary,spouseWages:s,filing,seniorCount:age===65?(filing==='mfj'?2:1):0}),r=E.estimateTaxes(p,age,ordinary,gain,ss,ordinary,0,s,0,0,0,0,1);for(const k of ['federal','niit','payroll','az','total','ssTaxable']){const error=Math.abs(r[k]-x[k]);worst=Math.max(worst,error);if(error>.01)failures.push({filing,age,ordinary,gain,ss,key:k,actual:r[k],expected:x[k]});}n++;}c.summary={calculations:n,components:n*6,worstDollarError:worst,failures};check('independent tax comparisons',failures.length,0); });
test('F26','Contract scalar and list numeric mutation refusals',()=> { const contract=JSON.parse(fs.readFileSync(path.join(root,'src/plan-value-contract.json'),'utf8')),base=b({age:65,endAge:66,spending:0});let n=0;const failures=[];function put(p,dotted,value){const keys=dotted.split('.');let o=p;for(const key of keys.slice(0,-1))o=o[key]||(o[key]={});o[keys.at(-1)]=value;}function probe(p,label){let v,r;try{v=V(p);r=E.runPlan(p);}catch(e){failures.push({label,thrown:e.message});n++;return;}if(v.valid||!r.calculationError||r.rows!==null)failures.push({label,valid:v.valid,code:r.calculationErrorCode,rows:r.rows&&r.rows.length});n++;}for(const entry of contract.scalars.filter(x=>x.type==='number'))for(const value of [NaN,Infinity,-Infinity,'123',null]){const p=structuredClone(base);put(p,entry.path,value);probe(p,entry.path+'='+String(value));}c.summary={mutations:n,failures};check('numeric mutation refusals',failures.length,0); });
test('F27','Malformed lists, duplicate routing IDs and nonserializable holdings',()=> { const failures=[];let n=0;const edits=[p=>p.accounts={},p=>p.accounts=[null],p=>p.accounts[0].balance=Infinity,p=>p.accounts[0].allocation.flat=NaN,p=>p.accounts.push(structuredClone(p.accounts[0])),p=>p.advanced.debts=[42],p=>p.retirement.otherIncomes=[null],p=>p.accounts[0].metadata=1n,p=>{p.accounts[0].metadata=p.accounts[0];}];for(const edit of edits){const p=b({age:65,endAge:66,spending:0});edit(p);let r;try{r=E.runPlan(p);}catch(e){failures.push({n,thrown:e.message});n++;continue;}if(!r.calculationError||r.rows!==null)failures.push({n,code:r.calculationErrorCode});n++;}c.summary={mutations:n,failures};check('controlled refusals',failures.length,0); });
test('F28','All nine spending policies at an independently simple opening state',()=> {const p=b({age:65,endAge:90,spending:10000,accounts:[a('r','rothIRA',100000)]});Object.assign(p.retirement,{withdrawalRate:4,floor:3000,ceiling:5000,vpwMinRate:0,vpwMaxRate:100,rmdMultiplier:100,rmdFloor:0});for(const [strategy,expected] of Object.entries({fixedReal:4000,fixedNominal:10000,constantPercent:4000,guardrails:4000,guyton:4000,vpw:4000,rmd:4000,floorCeiling:4000,incomeFirst:10000})){p.retirement.strategy=strategy;check(strategy,E.strategySpending(p,65,100000,100000,null,0,1,0,1,{},90,66,1,0,65,{}),expected);} });
test('F29','SS monthly early and delayed retirement factors',()=> { const p=b({age:40,retireAge:65,endAge:71,spending:0,ssBenefit:3000});p.retirement.ssCola=0;for(const [claim,factor] of [[62,.7],[62.5,.725],[64,.8],[65.5,.9],[67,1],[70,1.24]]){p.retirement.ssClaim=claim;check('claim '+claim,E.ssaBenefitAtClaim(p,'self',0,claim),Math.floor(3000*factor+1e-9)*12);} });
test('F30','Penalty age, account type and employer-separation boundaries',()=> {const p=b({age:54,retireAge:55,endAge:60,spending:0}),ira=a('i','traditionalIRA',100000),work=a('k','traditional401k',100000);check('IRA before 59.5',E.earlyWithdrawalPenaltyRate(p,59.49,ira),.1);check('IRA at 59.5',E.earlyWithdrawalPenaltyRate(p,59.5,ira),0);p.advanced.rule55=true;check('workplace before separation',E.earlyWithdrawalPenaltyRate(p,54.9,work),.1);check('current plan after 55 separation',E.earlyWithdrawalPenaltyRate(p,55,work),0);check('IRA does not inherit rule 55',E.earlyWithdrawalPenaltyRate(p,55,ira),.1);work.currentEmployerPlan=false;check('old employer plan does not qualify',E.earlyWithdrawalPenaltyRate(p,55,work),.1);ira._inheritedIra=true;check('beneficiary exception',E.earlyWithdrawalPenaltyRate(p,55,ira),0); });
test('F31','Finite input that overflows must not yield financial figures',()=> { const p=b({age:40,retireAge:70,endAge:42,spending:0,returnRate:100,accounts:[a('r','rothIRA',1e308)]}),r=E.runPlan(p);c.executions.push({result:r});check('controlled calculation refusal',r.status,'calculation_error');check('no numeric rows',r.rows,null);check('no success estimate',r.successRate,null); });
test('F32','Nested numeric field mutations start from validated records',()=> { const contract=JSON.parse(fs.readFileSync(path.join(root,'src/plan-value-contract.json'),'utf8')),p=b({age:65,endAge:66,spending:0});p.retirement.stages=[{id:'s',start:65,end:66,mode:'amount',value:0,annualChange:0,growthMode:'none'}];p.retirement.expenses=[{id:'e',age:65,amount:0}];p.retirement.otherIncomes=[stream(0)];p.advanced.otherAssets=[{id:'x',value:0,growth:0,availableAge:65,accessPct:100,liquidity:'liquid',available:true}];p.advanced.debts=[{id:'d',type:'otherDebt',rateType:'fixed',balance:0,rate:0,paymentMonthly:0,payoffAge:80}];check('unmutated nested fixture valid',V(p).valid,true);let n=0;const failures=[];function at(o,d){return d.split('.').reduce((x,k)=>x[k],o);}for(const list of contract.lists)for(const field of list.fields.filter(x=>x.type==='number'))for(const value of [NaN,Infinity,-Infinity,'123',null]){if(value===null&&field.nullable)continue;const q=structuredClone(p);at(q,list.list)[0][field.name]=value;const v=V(q),r=E.runPlan(q);if(v.valid||!r.calculationError||r.rows!==null)failures.push({path:list.list+'[0].'+field.name,value:String(value),valid:v.valid,code:r.calculationErrorCode});n++;}c.summary={mutations:n,failures};check('nested numeric mutations refused',failures.length,0); });
test('F33','Monte Carlo one-year distribution against a Gaussian quantile oracle',()=> { const p=b({age:40,retireAge:70,endAge:41,spending:0,accounts:[a('r','rothIRA',100000)]});Object.assign(p.assumptions,{method:'monteCarlo',runs:10000,seed:20261004,returnRate:5,volatility:10});p.advanced.assetsOn=false;const r=run(p),last=final(r); // Exact population quantiles of 100k*(1.05+.10*Z); 2k tolerance allows finite-sample variation, and is stated before execution.
  check('median Gaussian target',last.total,105000,2000);check('10th percentile Gaussian target',last.q10,105000-10000*1.2815515655446004,2000);check('90th percentile Gaussian target',last.q90,105000+10000*1.2815515655446004,2000);c.summary={paths:10000,populationOracle:true,samplingToleranceDollars:2000}; });
test('F34','Self-employment payroll and no-wage/property QBI matrix',()=> {let n=0,worst=0;const failures=[];for(const filing of ['single','mfj'])for(const selfWage of [0,100000,184500,250000])for(const profit of [400/.9235-.01,400/.9235,1000,20000,80000,300000])for(const spouseProfit of filing==='mfj'?[0,80000]:[0]){const spouseWage=filing==='mfj'?180000:0,p=b({age:40,couple:filing==='mfj',spouseAge:40,endAge:41,spending:0});const net=x=>x*.9235>=400?x*.9235:0,se=.124*(Math.min(net(profit),Math.max(0,184500-selfWage))+Math.min(net(spouseProfit),Math.max(0,184500-spouseWage)))+.029*(net(profit)+net(spouseProfit)),half=se/2,ordinary=selfWage+spouseWage+profit+spouseProfit-half,ot=Math.max(0,ordinary-standard[filing]),qbi=profit+spouseProfit-half,phase=Math.min(1,Math.max(0,(ot-(filing==='mfj'?403500:201750))/(filing==='mfj'?150000:75000)));let qd=Math.min(.2*qbi*(1-phase),.2*ot);if(qbi>=1000)qd=Math.max(qd,400);const fed=ordinaryTax(Math.max(0,ot-qd),filing),az=.025*Math.max(0,ordinary-standard[filing]),payroll=.062*(Math.min(184500,selfWage)+Math.min(184500,spouseWage))+.0145*(selfWage+spouseWage)+se+.009*Math.max(0,selfWage+spouseWage+net(profit)+net(spouseProfit)-(filing==='mfj'?250000:200000)),expected={federal:fed,az,payroll,seTax:se,seDeductibleHalf:half,qbiDeduction:qd,total:fed+az+payroll},r=E.estimateTaxes(p,40,selfWage+spouseWage+profit+spouseProfit,0,0,selfWage+spouseWage,0,spouseWage,profit,spouseProfit,0,0,1);for(const k of Object.keys(expected)){const error=Math.abs(r[k]-expected[k]);worst=Math.max(worst,error);if(error>.01)failures.push({filing,selfWage,spouseWage,profit,spouseProfit,key:k,actual:r[k],expected:expected[k]});}n++;}c.summary={calculations:n,components:n*7,worstDollarError:worst,failures};check('independent SE/QBI comparisons',failures.length,0); });
test('F35','Capital loss deduction and carry-forward worksheet controls',()=> { const p=b({age:40,endAge:41,spending:0});for(const [income,expectedCarry] of [[50000,2000],[0,5000],[17100,4000]]){const r=E.estimateTaxes(p,40,income,-5000,0,0,0,0,0,0,0,0,1);check('carry with income '+income,r.capitalLossCarryOut,expectedCarry);check('annual claimed deduction with income '+income,r.capitalLossDeduction,3000);} });
test('F36','Every engine-read boolean rejects truthy and falsey nonbooleans',()=> { const flags=JSON.parse(fs.readFileSync(path.join(root,'src/boolean-flag-contract.json'),'utf8')).flags.filter(x=>x.reader==='engine'),p=b({age:65,endAge:66,spending:0});p.advanced.debts=[{id:'d',type:'otherDebt',balance:0,rate:0,payoffAge:80}];p.advanced.otherAssets=[{id:'x',value:0,growth:0,availableAge:65,accessPct:100,liquidity:'liquid'}];check('unmutated boolean fixture valid',V(p).valid,true);const failures=[];let n=0;for(const flag of flags)for(const value of [null,0,1,'false','true',[],{}]){const q=structuredClone(p),keys=flag.path.replace(/\[\]/g,'.0').split('.');let target=q;for(const k of keys.slice(0,-1))target=target[k];target[keys.at(-1)]=value;const v=V(q),r=E.runPlan(q);if(v.valid||!r.calculationError||r.rows!==null)failures.push({path:flag.path,value,valid:v.valid,code:r.calculationErrorCode});n++;}c.summary={flags:flags.length,mutations:n,failures};check('boolean mutations refused',failures.length,0); });
const result={sourceRoot:root,createdAt:new Date().toISOString(),cases,summary:{cases:cases.length,checks:cases.reduce((n,x)=>n+x.checks.length,0),executions:cases.reduce((n,x)=>n+x.executions.length,0),passed:cases.filter(x=>x.pass).length,failed:cases.filter(x=>!x.pass).map(x=>({id:x.id,name:x.name,checks:x.checks.filter(y=>!y.passed),error:x.error}))}};
if(output)fs.writeFileSync(output,JSON.stringify(result,null,2));console.log(JSON.stringify(result.summary,null,2));process.exitCode=result.summary.failed.length?1:0;
