/* Independent R54 audit companion. Usage: node <this file> <source root> <output.json>.
 * The 20 cases below run without an adapter. Financial oracles are explicit arithmetic.
 * UI cases restore through the real file input and record every posted plan. A stand-in
 * Worker executes the audited runScenario; real Chrome Worker checks are separately recorded.
 * Only the source tree and scratch output are read/written. No production repair is made.
 */
'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const ROOT=path.resolve(process.argv[2]||'.'),OUT=path.resolve(process.argv[3]||'r54-focused.json');
const L=require(path.join(ROOT,'audit/S5AA/R40/S5AA_R40_CONSERVATION_GRID/lib.js'));
const E=L.h.engine,V=require(path.join(ROOT,'src/scenario-validator.js')).validateScenario;
const H=require(path.join(ROOT,'tests/lib/harness.js')),KEY='investment-calculator-v2c';
const cases=[],clone=x=>structuredClone(x),at=(r,a)=>r.rows?.find(x=>Math.abs(x.age-a)<1e-8);
function check(c,label,actual,expected,tol=0){const pass=typeof expected==='number'?Number.isFinite(actual)&&Math.abs(actual-expected)<=tol:JSON.stringify(actual)===JSON.stringify(expected);c.checks.push({label,actual,expected,tolerance:tol,pass});}
function base(o={}){const p=L.basePlan({age:60,retireAge:60,endAge:61,spending:0,dividendOn:true,dividendYield:0,accounts:[L.account('r','rothIRA',100000,{contributionBasis:100000})],...o});p.profile.rothFirstContributionYear=2000;p.retirement.ssCola=0;return p;}
function begin(id,name,p){const c={id,name,plan:clone(p),checks:[]};cases.push(c);return c;}
function run(c,p=c.plan){const v=V(clone(p)),r=E.runPlan(clone(p));check(c,'validator accepts',v.valid,true);check(c,'engine status',r.status,'ok');c.result=r;return r;}
function figures(c,r,entries){for(const [age,key,expected]of entries)check(c,key+' at '+age,at(r,age)?.[key],expected,1e-6);}
function idle(s){return !/is-running/.test(s.d.getElementById('v2-performance').className)&&!/Waiting/.test(s.d.getElementById('v2-performance').textContent);}
function installWorker(w){const posted=[],replies=[];w.URL.createObjectURL=()=> 'blob:r54-independent';w.URL.revokeObjectURL=()=>{};w.Worker=function(){this.terminate=()=>{};this.postMessage=m=>{const p=JSON.parse(JSON.stringify(m.plan));posted.push(p);setTimeout(()=>{const result=E.runScenario(clone(p));replies.push(result);if(this.onmessage)this.onmessage({data:{id:m.id,result}});},0);};};return {posted,replies};}
async function importInto(s,plans){const input=s.d.getElementById('v2-import-settings');Object.defineProperty(input,'files',{value:[new s.w.File([JSON.stringify({format:KEY,version:2,app:{version:2,edition:'2C',page:'setup',complexity:'advanced',theme:'auto',compare:false,active:0,scenarios:plans}})],'audit.json',{type:'application/json'})],configurable:true});s.d.getElementById('v2-status').textContent='';input.dispatchEvent(new s.w.Event('change',{bubbles:true}));await H.waitFor(()=>s.status()!==''&&idle(s),{window:s.w,timeoutMs:20000});}
async function restore(p){const dom=await H.loadCalculator({artifact:'fresh'}),w=dom.window,d=w.document;const s={w,d,...installWorker(w),saved:()=>JSON.parse(w.localStorage.getItem(KEY)).scenarios[0],status:()=>d.getElementById('v2-status').textContent};await importInto(s,[p]);return s;}
async function edit(s,id,value){const n=s.posted.length,e=s.d.getElementById(id);H.setValue(e,String(value));e.dispatchEvent(new s.w.Event('blur'));await H.waitFor(()=>s.posted.length>n&&s.replies.length===s.posted.length&&idle(s),{window:s.w,timeoutMs:20000});}
function snapshot(c,s){c.saved=clone(s.saved());c.posted=clone(s.posted.at(-1));c.result=clone(s.replies.at(-1));c.status=s.status();}
function preserved(c,s,paths){for(const dotted of paths){const get=o=>dotted.split('.').reduce((x,k)=>x?.[k],o);check(c,dotted+' saved',get(s.saved()),get(c.plan));check(c,dotted+' posted',get(s.posted.at(-1)),get(c.plan));}}
async function ui(id,name,p,body){const c=begin(id,name,p),s=await restore(p);try{check(c,'initial import projected',s.replies.at(-1)?.status,'ok');await body(c,s);snapshot(c,s);}finally{s.w.close();}}
const put=(p,k,v)=>{const a=k.split('.'),last=a.pop();a.reduce((x,key)=>x[key],p)[last]=v;};
(async()=>{
 // F01: three annual charges of 5%, on a flat qualified Roth: 100000 * .95^n.
 {const p=base({endAge:63});p.assumptions.fee=5;const c=begin('F01','5% fee compounds for three years',p),r=run(c);figures(c,r,[...Array.from({length:3},(_,i)=>[61+i,'roth',100000*.95**(i+1)]),[63,'taxes',0]]);}
 // F02: constant-percent spending is reset to 25% of each annual opening balance.
 {const p=base({endAge:63,strategy:'constantPercent'});p.retirement.withdrawalRate=25;const c=begin('F02','25% withdrawals reset each year',p),r=run(c);for(let n=1;n<=3;n++)figures(c,r,[[60+n,'spending',25000*.75**(n-1)],[60+n,'roth',100000*.75**n],[60+n,'taxes',0]]);}
 // F03/F04: an adjustment of zero changes spending by a factor of one on either guardrail.
 for(const [id,ret]of [['F03',-30],['F04',30]]){const p=base({endAge:62,returnRate:ret,strategy:'guardrails'});Object.assign(p.retirement,{withdrawalRate:4,adjustment:0,upperGuardrail:20,lowerGuardrail:20,floor:0,ceiling:1e9});const c=begin(id,'Zero guardrail adjustment, return '+ret+'%',p),r=run(c);figures(c,r,[[61,'spending',4000],[62,'spending',4000]]);}
 // F05/F06: cost the year of death at couple spending, then reduce to 25% for the survivor.
 for(const [id,owner]of [['F05','self'],['F06','spouse']]){const p=base({couple:true,age:70,spouseAge:70,retireAge:70,endAge:73,spending:40000,accounts:[L.account('r','rothIRA',1000000,{contributionBasis:1000000})]});p.profile.spouseRothFirstContributionYear=2000;Object.assign(p.retirement,{survivor:true,survivorSpendingReduction:75,selfLife:120,spouseLife:120});p.retirement[owner+'Life']=70.5;const c=begin(id,'75% spending reduction after '+owner+' death',p),r=run(c);figures(c,r,[[71,'spending',40000],[72,'spending',10000],[73,'spending',10000],[73,'roth',940000],[73,'taxes',0]]);}
 // F07: the entered dividend yield halves each year. Retained dividends leave the original account,
 // and are kept in a separate cash account; total wealth remains 100000. The second yield is 2% of 96000 and the third is 1% of 94080. Below deductions: tax zero.
 {const p=base({endAge:63,dividendYield:4,accounts:[L.account('t','taxable',100000,{basisPct:100})]});p.retirement.dividendGrowth=-50;p.retirement.dividendStart=60;const c=begin('F07','Dividend growth -50% and cash conservation',p),r=run(c);figures(c,r,[[61,'dividends',4000],[62,'dividends',1920],[63,'dividends',940.8],[63,'total',100000],[63,'taxes',0]]);const tap=L.runTapped(p).taps.at(-1);check(c,'original taxable account',tap.balances.find(a=>a.id==='t').b,93139.2,1e-6);check(c,'retained dividend cash',tap.balances.filter(a=>a.id!=='t').reduce((n,a)=>n+a.b,0),6860.8,1e-6);}
 // F08: same Monte Carlo seed and 24 paths, with zero volatility/returns: all terminal values 75000.
 {const p=base({strategy:'constantPercent'});Object.assign(p.assumptions,{method:'monteCarlo',runs:24,seed:37});p.retirement.withdrawalRate=25;await ui('F08','Restore 24 Monte Carlo paths without rounding',p,async(c,s)=>{preserved(c,s,['assumptions.runs','assumptions.seed','retirement.withdrawalRate']);check(c,'requested paths',s.replies.at(-1).requestedPathCount,24);figures(c,s.replies.at(-1),[[61,'spending',25000],[61,'roth',75000]]);check(c,'status names 24 simulations',s.status().includes('24 simulations'),true);});}
 // U09: preserve a horizon over 100 through an unrelated name edit; 40 full annual steps.
 await ui('U09','End age 110 survives unrelated edit',base({age:70,retireAge:65,endAge:110}),async(c,s)=>{await edit(s,'v2-name','Renamed');preserved(c,s,['profile.endAge','profile.retireAge']);check(c,'41 rows',s.replies.at(-1).rows?.length ?? 0,41);figures(c,s.replies.at(-1),[[110,'roth',100000],[110,'taxes',0]]);});
 // U10: original R53-01: six historical pension COLA dates remain when only current age changes.
 {const p=base({age:70,retireAge:65,endAge:71,pension:10000});p.retirement.pensionCola=10;p.advanced.surplusPolicy='invest';await ui('U10','Current age edit preserves historical retirement and pension COLA',p,async(c,s)=>{await edit(s,'v2-age',70.3);preserved(c,s,['profile.retireAge','profile.endAge']);check(c,'edited age',s.saved().profile.age,70.5);check(c,'shown retirement',s.d.getElementById('v2-retire').value,'65.0');const pension=10000*1.1**5.5*.5;figures(c,s.replies.at(-1),[[71,'income',pension],[71,'total',100000+pension],[71,'roth',100000],[71,'taxes',0]]);});}
 // U11: a changed end age must stay below retirement and refuse, then recover after correction.
 await ui('U11','End-age refusal and recovery',base({age:60,retireAge:65,endAge:70}),async(c,s)=>{await edit(s,'v2-end',63);check(c,'end saved as edited',s.saved().profile.endAge,63);preserved(c,s,['profile.age','profile.retireAge']);check(c,'named refusal',s.replies.at(-1).calculationErrorCode,'SCENARIO_END_AGE_BEFORE_RETIREMENT');check(c,'status is refusal',s.status().includes('No projection for this scenario:'),true);check(c,'no rows for refused plan',s.replies.at(-1).rows?.length ?? 0,0);c.refused=clone(s.replies.at(-1));await edit(s,'v2-end',70);check(c,'recovered status',s.replies.at(-1).status,'ok');figures(c,s.replies.at(-1),[[70,'roth',100000]]);});
 // U12: rounding is the edited retirement field's own rule; it cannot move the end age.
 await ui('U12','Retirement edit cannot extend the horizon',base({age:60,retireAge:65,endAge:70}),async(c,s)=>{await edit(s,'v2-retire',72.3);check(c,'own half-year rounding',s.saved().profile.retireAge,72.5);preserved(c,s,['profile.age','profile.endAge']);check(c,'named refusal',s.replies.at(-1).calculationErrorCode,'SCENARIO_END_AGE_BEFORE_RETIREMENT');check(c,'no rows',s.replies.at(-1).rows?.length ?? 0,0);});
 // U13: a start after the end keeps both other ages, with the original start-horizon refusal.
 await ui('U13','Start edit cannot move retirement or end',base({age:70,retireAge:65,endAge:75}),async(c,s)=>{await edit(s,'v2-age',76);preserved(c,s,['profile.retireAge','profile.endAge']);check(c,'named refusal',s.replies.at(-1).calculationErrorCode,'SCENARIO_END_AGE_BEFORE_START');check(c,'status is refusal',s.status().includes('No projection for this scenario:'),true);check(c,'no rows',s.replies.at(-1).rows?.length ?? 0,0);});
 // U14: restored return/inflation/salary-growth/pension-COLA/reserve values outside blur-only
 // UI ranges remain valid under the owner's D8 reading. No event means no edit.
 {const p=base({returnRate:25,inflation:20});Object.assign(p.employment,{growth:35});p.retirement.pensionCola=15;p.advanced.reserveYears=12;await ui('U14','Untouched blur preserves D8 values',p,async(c,s)=>{for(const id of ['v2-return','v2-inflation','v2-salary-growth','v2-pension-cola','v2-reserve-years'])s.d.getElementById(id).dispatchEvent(new s.w.Event('blur'));await edit(s,'v2-name','D8 retained');preserved(c,s,['assumptions.returnRate','assumptions.inflation','employment.growth','retirement.pensionCola','advanced.reserveYears']);figures(c,s.replies.at(-1),[[61,'roth',125000]]);});}
 // U15: an edit remains an edit even after blur returns to the original displayed 2.5 years.
 {const p=base();p.advanced.ltcYears=2.5;await ui('U15','Typed-then-rounded text counts as an edit',p,async(c,s)=>{await edit(s,'v2-ltc-years',2.6);check(c,'edited LTC years use save rounding',s.saved().advanced.ltcYears,3);check(c,'posted LTC years',s.posted.at(-1).advanced.ltcYears,3);preserved(c,s,['profile.age','profile.retireAge','profile.endAge','assumptions.fee']);figures(c,s.replies.at(-1),[[61,'roth',100000]]);});}
 // U16: section extension keys, older scalar keys, custom account metadata, and a valid unusual
 // manual withdrawal order survive. This deliberately audits beyond numeric KEPT_STATIC fields.
 {const p=base();Object.assign(p.retirement,{ssFra:60,pensionAge:65,pensionStart:67,manualOrder:'roth,hsa,preTax,taxable',extension:{nested:[1,2,3]}});p.profile.extension={ok:true};p.employment.extension='keep';p.assumptions.extension=0;p.accounts[0].extension={ledger:'keep'};await ui('U16','Hidden and nonnumeric restored values survive',p,async(c,s)=>{await edit(s,'v2-name','Metadata retained');preserved(c,s,['retirement.ssFra','retirement.pensionAge','retirement.pensionStart','retirement.manualOrder','retirement.extension','profile.extension','employment.extension','assumptions.extension','accounts.0.extension']);figures(c,s.replies.at(-1),[[61,'roth',100000]]);});}
 // N17: independently enumerate all 28 newly adopted bounds, both exact edges and just beyond.
 {const p=base(),c=begin('N17','28 shared range families: edges and adjacent refusals',p);const ranges=[['profile.priorIncomeThisYear',0,1e9],['advanced.medicareInflation',-99,100],['advanced.partDPremium',0,100000],['employment.salary',0],['employment.spouseSalary',0],['assumptions.fee',0,5],['assumptions.volatility',0],['retirement.spending',0],['retirement.withdrawalRate',0,25],['retirement.upperGuardrail',1],['retirement.lowerGuardrail',1],['retirement.adjustment',0],['retirement.floor',0],['retirement.ceiling',0],['retirement.vpwMinRate',0,25],['retirement.vpwMaxRate',0,100],['retirement.rmdMultiplier',0,200],['retirement.rmdFloor',0],['retirement.flexibility',0,50],['retirement.dividendYield',0,20],['retirement.dividendQualified',0,100],['retirement.dividendGrowth',-50,20],['retirement.ssBenefit',0],['retirement.spouseSS',0],['retirement.ssCola',0,15],['retirement.survivorSpendingReduction',0,75],['advanced.correlation',-1,1],['advanced.healthInflation',0,100]];c.mutations=[];for(const [key,min,max]of ranges)for(const [value,accept]of [[min,true],[min-.01,false],...(max===undefined?[]:[[max,true],[max+.01,false]])]){const q=base();put(q,key,value);const v=V(clone(q)),r=E.runPlan(clone(q));check(c,key+' '+value+' validator',v.valid,accept);check(c,key+' '+value+' engine',r.calculationErrorCode||null,accept?null:'SCENARIO_PLAN_VALUE_OUT_OF_RANGE');if(!accept)check(c,key+' '+value+' no rows',r.rows?.length ?? 0,0);c.mutations.push({path:key,value,accepted:accept,issues:v.issues,code:r.calculationErrorCode||null});}run(c);figures(c,c.result,[[61,'roth',100000]]);}
 // N18: seed 0, negative, or fractional must refuse; absent seed and whole seed remain supported.
 {const c=begin('N18','Entered seed integer contract and absent fallback',base());for(const seed of [0,-3,1.5,NaN,Infinity,'7']){const p=base();p.assumptions.seed=seed;const v=V(clone(p)),r=E.runPlan(clone(p));check(c,'seed '+String(seed)+' refused by validator',v.valid,false);check(c,'seed '+String(seed)+' refused by engine',r.calculationError,true);check(c,'seed '+String(seed)+' no rows',r.rows?.length ?? 0,0);}for(const seed of [undefined,1,37]){const p=base();Object.assign(p.assumptions,{method:'monteCarlo',runs:24});if(seed===undefined)delete p.assumptions.seed;else p.assumptions.seed=seed;const r=E.runPlan(clone(p));check(c,'seed '+String(seed)+' engine ok',r.status,'ok');check(c,'seed '+String(seed)+' 24 paths',r.requestedPathCount,24);figures(c,r,[[61,'roth',100000]]);}}
 // N19: both prior MAGI keys refuse below zero even with health off. Null/absent mean not
 // supplied; zero is an explicit return. All three keep the flat Roth balance unchanged.
 {const c=begin('N19','Negative prior MAGI closed on both engine routes',base());for(const key of ['irmaaMagiTwoYearsBefore','irmaaMagiOneYearBefore'])for(const value of [-.01,-5,0,null,undefined]){const p=base();if(value!==undefined)p.advanced[key]=value;else delete p.advanced[key];const v=V(clone(p)),r=E.runPlan(clone(p)),scenario=E.runScenario(clone(p));check(c,key+' '+String(value)+' validator',v.valid,!(value<0&&value!==null));check(c,key+' '+String(value)+' runPlan',r.calculationErrorCode||null,value<0&&value!==null?'SCENARIO_NEGATIVE_PRIOR_MAGI':null);check(c,key+' '+String(value)+' runScenario',scenario.calculationErrorCode||null,value<0&&value!==null?'SCENARIO_NEGATIVE_PRIOR_MAGI':null);if(value===null||value===undefined||value>=0)figures(c,r,[[61,'roth',100000]]);}}
 // N20: a multi-scenario backup with one invalid seed and negative MAGI is atomic: valid
 // active plan, balance, and browser-storage bytes remain untouched after refusal.
 await ui('N20','Invalid backup leaves valid financial plan and storage intact',base(),async(c,s)=>{const before=s.w.localStorage.getItem(KEY),n=s.posted.length,bad=base();bad.assumptions.seed=0;bad.advanced.irmaaMagiTwoYearsBefore=-5;await importInto(s,[base({spending:9000}),bad]);check(c,'storage bytes unchanged',s.w.localStorage.getItem(KEY),before);check(c,'no new worker plans',s.posted.length,n);check(c,'import names refusal',/seed|MAGI|irmaaMagi/.test(s.status()),true);figures(c,s.replies.at(-1),[[61,'roth',100000],[61,'taxes',0]]);});
 for(const c of cases)c.pass=c.checks.every(x=>x.pass);
 const summary={simulations:cases.length,checks:cases.reduce((s,c)=>s+c.checks.length,0),passed:cases.filter(c=>c.pass).length,failed:cases.filter(c=>!c.pass).map(c=>c.id)};
 const sourceSha=cp.execFileSync('git',['-c','core.commitGraph=false','rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim();
 fs.writeFileSync(OUT,JSON.stringify({sourceSha,summary,cases},null,2));console.log(JSON.stringify(summary,null,2));for(const c of cases)for(const x of c.checks.filter(x=>!x.pass))console.log(c.id,x.label,'actual',JSON.stringify(x.actual),'expected',JSON.stringify(x.expected));if(summary.failed.length)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=2;});
