/* Independent R53 audit. Usage: node <this file> <source root> <output.json>.
 * No companion adapter. All projected plans use retireAge <= endAge.
 * Financial expectations below are arithmetic, not outputs copied from the engine.
 * UI checks use the real Restore backup input and a fresh artifact in jsdom.
 */
'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const ROOT=path.resolve(process.argv[2]||'.'),OUT=path.resolve(process.argv[3]||'r53-focused.json');
const L=require(path.join(ROOT,'audit/S5AA/R40/S5AA_R40_CONSERVATION_GRID/lib.js'));
const E=L.h.engine,V=require(path.join(ROOT,'src/scenario-validator.js')).validateScenario;
const H=require(path.join(ROOT,'tests/lib/harness.js')),KEY='investment-calculator-v2c';
const cases=[];const clone=x=>structuredClone(x),at=(r,a)=>r.rows.find(x=>Math.abs(x.age-a)<1e-8);
function check(c,label,actual,expected,tol=0){const pass=typeof expected==='number'?Number.isFinite(actual)&&Math.abs(actual-expected)<=tol:JSON.stringify(actual)===JSON.stringify(expected);c.checks.push({label,actual,expected,tolerance:tol,pass});}
function base(o={}){const p=L.basePlan({spending:0,dividendOn:true,dividendYield:0,...o});p.profile.rothFirstContributionYear=2000;p.retirement.ssCola=0;return p;}
let jobId=0;
function job(amount,start,end,owner='self',type='employment'){return {id:'j'+(++jobId),name:'Dated work',type,owner,amount,start,end,growth:0,growthMode:'fixed'};}
function grace(o={}){const p=base({age:65,retireAge:65.5,endAge:66,salary:100000,ssBenefit:2000,accounts:[L.account('r','rothIRA',100000)],...o});p.retirement.ssClaim=o.claim??65.5;p.retirement.otherIncomes=o.streams||[];return p;}
function project(id,name,p,expected){const c={id,name,plan:clone(p),checks:[]};const v=V(clone(p));check(c,'validator accepts',v.valid,true);const r=E.runPlan(clone(p));check(c,'engine status',r.status,'ok');c.result=r;for(const [age,field,value]of expected)check(c,field+' at '+age,at(r,age)?.[field],value,.01);cases.push(c);return c;}
// SS = row income less independently summed salary and stream cash.
function ss(id,name,p,wages,expected,rowAge=p.profile.endAge){return project(id,name,p,[[rowAge,'income',wages+expected]]);}
async function restore(plans){const dom=await H.loadCalculator({artifact:'fresh'}),w=dom.window,d=w.document,input=d.getElementById('v2-import-settings'),status=d.getElementById('v2-status');const initial=w.localStorage.getItem(KEY);Object.defineProperty(input,'files',{value:[new w.File([JSON.stringify({format:KEY,version:2,app:{version:2,edition:'2C',page:'setup',complexity:'standard',theme:'auto',compare:false,active:0,scenarios:plans}})],'audit.json',{type:'application/json'})],configurable:true});status.textContent='';input.dispatchEvent(new w.Event('change',{bubbles:true}));await H.waitFor(()=>status.textContent!==''&&!/is-running/.test(d.getElementById('v2-performance').className),{window:w,timeoutMs:20000});return {w,d,initial,status:status.textContent,saved:()=>JSON.parse(w.localStorage.getItem(KEY)).scenarios};}
async function edit(s,id,value,predicate){H.setValue(s.d.getElementById(id),String(value));s.d.getElementById(id).dispatchEvent(new s.w.Event('blur'));await H.waitFor(()=>predicate(s.saved()),{window:s.w,timeoutMs:20000});}
const KEPT={'v2-age':['profile','age'],'v2-retire':['profile','retireAge'],'v2-end':['profile','endAge'],'v2-spouse-age':['profile','spouseAge'],'v2-contribution-stop':['employment','contributionStop'],'v2-dividend-start':['retirement','dividendStart'],'v2-ss-claim':['retirement','ssClaim'],'v2-spouse-claim':['retirement','spouseClaim'],'v2-self-life':['retirement','selfLife'],'v2-spouse-life':['retirement','spouseLife'],'v2-transfer-age':['advanced','transferAge'],'v2-spouse-retire':['profile','spouseRetireAge'],'v2-spending-start':['retirement','spendingStartAge'],'v2-conversion-start':['advanced','conversionStartAge'],'v2-health-coverage-end':['advanced','healthCoverageEndAge'],'v2-ltc-onset':['advanced','ltcOnsetAge'],'v2-medicare-start':['profile','medicareStartAge'],'v2-spouse-medicare-start':['profile','spouseMedicareStartAge']};
function precisionPlan(){const p=base({couple:true,age:70.25,spouseAge:66.25,retireAge:65.25,endAge:72.75,pension:10000,accounts:[L.account('r','rothIRA',100000,{contributionBasis:100000})]});Object.assign(p.profile,{spouseRetireAge:67.25,medicareStartAge:65.25,spouseMedicareStartAge:65.75});p.employment.contributionStop=64.75;Object.assign(p.retirement,{pensionCola:2,dividendStart:70.75,ssClaim:69.75,spouseClaim:67.25,selfLife:94.25,spouseLife:96.75,spendingStartAge:68.25,manualOrder:'roth,hsa,taxable,preTax'});Object.assign(p.advanced,{transferAge:70.75,conversionStartAge:68.75,healthCoverageEndAge:69.25,ltcOnsetAge:90.25});return p;}
function monthlyOracleGrid(){
 let seed=20261004;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const rates=[0,1,12000,12480,24480,24492,36000,60000],results=[];
 for(let i=0;i<400;i++){
  const streams=[];for(let j=0;j<1+Math.floor(random()*5);j++){const from=Math.floor(random()*4)/4,to=from+(1+Math.floor(random()*(4-from*4)))/4;streams.push(job(rates[Math.floor(random()*rates.length)],65+from,65+to,'self',random()<.25?'selfEmployment':'employment'));}
  const p=grace({endAge:68,streams});
  // Independent month enumeration: six checks of1800; wages2040/month and SE services determine protection.
  const earnings=50000+streams.reduce((s,j)=>s+j.amount*(j.end-j.start)*(j.type==='selfEmployment'?.9235:1),0);
  let service=0;for(let month=6;month<12;month++){const age=65+(month+.5)/12,active=streams.filter(j=>age>=j.start&&age<j.end),wages=active.filter(j=>j.type==='employment').reduce((s,j)=>s+j.amount/12,0);if(wages>2040||active.some(j=>j.type==='selfEmployment'&&j.amount>0))service++;}
  const withheld=Math.min(10800,Math.max(0,earnings-24480)/2,service*1800),expectedSS=10800-withheld,credited=Math.min(service,Math.ceil(withheld/1800-1e-9));
  // Each fully or partially withheld month earns one reduction-factor credit. No wages after first year.
  const expectedFra=12*Math.floor(2000*(1-(18-credited)*5/900)+1e-9),cash=50000+streams.reduce((s,j)=>s+j.amount*(j.end-j.start),0),r=E.runPlan(clone(p)),actualSS=at(r,66)?.income-cash,actualFra=at(r,68)?.income;
  results.push({case:i,streams,service,earnings,expectedSS,actualSS,credited,expectedFra,actualFra,pass:V(clone(p)).valid&&r.status==='ok'&&Math.abs(actualSS-expectedSS)<=.01&&Math.abs(actualFra-expectedFra)<=.01});
 }
 return {seed:20261004,cases:400,financialChecks:800,failed:results.filter(x=>!x.pass).length,results};
}
(async()=>{
 // 18 months early: 2000*(1-18*5/900)=1800; six benefit months=10800.
 // Salary 100000 for half a year=50000. All G01-G06 annual deductions are large enough to exhaust service-month caps.
 ss('G01','Low wages then high wages after claim',grace({streams:[job(12000,65.5,65.75),job(36000,65.75,66)]}),62000,5400);
 ss('G02','High wages then low wages after claim',grace({streams:[job(36000,65.5,65.75),job(12000,65.75,66)]}),62000,5400);
 ss('G03','Two individually small wages exceed monthly limit together',grace({streams:[job(12000,65.5,66),job(12600,65.5,66)]}),62300,0);
 ss('G04','Combined wages exactly equal monthly limit',grace({streams:[job(12000,65.5,66),job(12480,65.5,66)]}),62240,10800);
 ss('G05','Tiny SE profit in three months triggers disclosed services rule',grace({streams:[job(1,65.5,65.75,'self','selfEmployment')]}),50000.25,5400);
 ss('G06','SE profit ends at claim; no later services',grace({streams:[job(60000,65,65.5,'self','selfEmployment')]}),80000,10800);
 // Younger spouse born 1962: 30 early months -> floor(2000*(1-30*5/900))=1666; six months=9996.
 const s7=grace({couple:true,spouseAge:64,salary:0,spouseSalary:100000,ssBenefit:0,spouseSS:2000,streams:[job(12000,64.5,65,'spouse')]});s7.profile.spouseRetireAge=64.5;s7.retirement.spouseClaim=64.5;s7.retirement.ssClaim=67;
 ss('G07','Younger spouse dates remain on own clock',s7,56000,9996);
 const s8=grace({couple:true,spouseAge:65,salary:200000,spouseSalary:100000,ssBenefit:0,spouseSS:2000,streams:[job(12000,65.5,66,'spouse')]});s8.profile.spouseRetireAge=65.5;s8.retirement.spouseClaim=65.5;s8.retirement.ssClaim=67;
 ss('G08','Other owner salary does not mark spouse benefit months as service',s8,156000,10800);
 ss('G09','Post-retirement job ends at delayed claim',grace({retireAge:65.25,streams:[job(60000,65.25,65.5)]}),40000,10800);
 // Claim65.25:21 early months, floor1766; 9checks15894. Salary12000*.75=9000; preclaim job70000*.25=17500.
 // Annual excess2020/2=1010, but every benefit month has only1000 salary/month: all are non-service even before retirement.
 ss('G10','Low salary before retirement also earns monthly protection',grace({salary:12000,retireAge:65.75,claim:65.25,streams:[job(70000,65,65.25)]}),26500,15894);
 // FRA year:6 early months -> floor1933;6checks11598. Monthly limit65160/12=5430.
 ss('G11','FRA year combined wages exactly at higher limit',grace({age:66,retireAge:66.5,endAge:67,claim:66.5,salary:200000,streams:[job(30000,66.5,67),job(35160,66.5,67)]}),132580,11598);
 ss('G12','FRA year combined wages one dollar/month above limit',grace({age:66,retireAge:66.5,endAge:67,claim:66.5,salary:200000,streams:[job(30000,66.5,67),job(35172,66.5,67)]}),132586,0);
 ss('G13','Partial final year keeps three protected benefit months',grace({endAge:65.75,streams:[job(12000,65.5,65.75)]}),53000,5400);
 const p14=precisionPlan(),c14={id:'U14',name:'All eighteen restored dates survive focus, blur and salary edit',plan:clone(p14),checks:[]};cases.push(c14);let ui=await restore([p14]);try{for(const[id,[g,k]]of Object.entries(KEPT)){check(c14,g+'.'+k+' saved',ui.saved()[0][g][k],p14[g][k]);check(c14,id+' shown',Number(ui.d.getElementById(id).value),p14[g][k]);ui.d.getElementById(id).dispatchEvent(new ui.w.Event('blur'));}await edit(ui,'v2-salary',1000,q=>q[0].employment.salary===1000);for(const[g,k]of Object.values(KEPT))check(c14,g+'.'+k+' after unrelated edit',ui.saved()[0][g][k],p14[g][k]);const r=E.runPlan(clone(ui.saved()[0]));c14.saved=ui.saved()[0];c14.result=r;check(c14,'first pension row',at(r,71).income,10000*1.02**5*.75,.01);}finally{ui.w.close();}
 const p15=base({age:60,endAge:61,spending:10000,manualOrder:'roth,hsa,preTax,taxable',accounts:[L.account('r','rothIRA',50000,{contributionBasis:50000}),L.account('c','taxable',50000)]});p15.name='Roth first';const q15=clone(p15);q15.id='other-scenario';q15.name='Cash first';q15.retirement.manualOrder='taxable,hsa,preTax,roth';const c15={id:'U15',name:'Scenario switches keep separate unlisted orders',plan:clone(p15),secondPlan:clone(q15),checks:[]};cases.push(c15);ui=await restore([p15,q15]);try{ui.d.querySelectorAll('#v2-scenario-tabs button')[1].click();check(c15,'second order shown',ui.d.getElementById('v2-manual-order').value,q15.retirement.manualOrder);ui.d.querySelectorAll('#v2-scenario-tabs button')[0].click();check(c15,'first order shown',ui.d.getElementById('v2-manual-order').value,p15.retirement.manualOrder);await edit(ui,'v2-salary',1,q=>q[0].employment.salary===1);const saved=ui.saved();c15.saved=saved;for(let i=0;i<2;i++){check(c15,'stored order '+i,saved[i].retirement.manualOrder,[p15,q15][i].retirement.manualOrder);const r=E.runPlan(clone(saved[i]));check(c15,'Roth closing '+i,at(r,61).roth,i===0?40000:50000,.01);check(c15,'cash closing '+i,at(r,61).taxable,i===0?50000:40000,.01);}}finally{ui.w.close();}
 const p16=base({age:59,endAge:60,accounts:[L.account('r','rothIRA',100000,{contributionBasis:0}),L.account('c','taxable',0)]});Object.assign(p16.advanced,{transferOn:true,transferFrom:'r',transferTo:'c',transferAmount:10000,transferAge:59.25});const c16={id:'U16',name:'Restored pre-59.5 draw and explicit edit across qualification',plan:clone(p16),checks:[]};cases.push(c16);ui=await restore([p16]);try{check(c16,'untouched date',ui.saved()[0].advanced.transferAge,59.25);check(c16,'pre59.5 tax',at(E.runPlan(clone(ui.saved()[0])),60).taxSettled,1000,.01);await edit(ui,'v2-transfer-age',59.6,q=>q[0].advanced.transferAge===59.5);check(c16,'edited date',ui.saved()[0].advanced.transferAge,59.5);check(c16,'qualified tax',at(E.runPlan(clone(ui.saved()[0])),60).taxSettled,0,.01);check(c16,'age unaffected',ui.saved()[0].profile.age,59);c16.saved=ui.saved()[0];}finally{ui.w.close();}
 const p17=precisionPlan(),c17={id:'U17',name:'Editing one optional date leaves the other seventeen untouched',plan:clone(p17),checks:[]};cases.push(c17);ui=await restore([p17]);try{await edit(ui,'v2-conversion-start',68.3,q=>q[0].advanced.conversionStartAge===68.5);check(c17,'edited date half-rounds',ui.saved()[0].advanced.conversionStartAge,68.5);for(const[id,[g,k]]of Object.entries(KEPT))if(id!=='v2-conversion-start')check(c17,g+'.'+k+' untouched',ui.saved()[0][g][k],p17[g][k]);c17.saved=ui.saved()[0];}finally{ui.w.close();}
 const p18=base({age:40,retireAge:60,endAge:41,accounts:[L.account('r','rothIRA',100000)]}),c18={id:'N18',name:'Primary horizon refused in every engine method and actual import',plan:clone(p18),checks:[]};cases.push(c18);check(c18,'validator code',V(clone(p18)).issues.filter(x=>x.severity==='ERROR').map(x=>x.code),['END_AGE_BEFORE_RETIREMENT']);for(const method of ['simple','historical','monteCarlo']){const q=clone(p18);q.assumptions.method=method;q.assumptions.runs=100;const r=E.runPlan(q);check(c18,method+' refusal',r.calculationErrorCode,'SCENARIO_END_AGE_BEFORE_RETIREMENT');check(c18,method+' rows',r.rows,null);}ui=await restore([p18]);try{check(c18,'import mentions rule',/before retireAge/.test(ui.status),true);check(c18,'stored scenarios byte unchanged',ui.w.localStorage.getItem(KEY),ui.initial);c18.importStatus=ui.status;}finally{ui.w.close();}
 const p19=base({age:60,retireAge:60.5,endAge:59.75}),c19={id:'N19',name:'Start-age refusal takes precedence; narrow retirement shortfall also refused',plan:clone(p19),checks:[]};cases.push(c19);check(c19,'validator only start code',V(clone(p19)).issues.filter(x=>x.severity==='ERROR').map(x=>x.code),['END_AGE_BEFORE_START']);check(c19,'engine start code',E.runPlan(clone(p19)).calculationErrorCode,'SCENARIO_END_AGE_BEFORE_START');p19.profile.endAge=60.5-1e-8;check(c19,'strict retirement comparison',E.runPlan(clone(p19)).calculationErrorCode,'SCENARIO_END_AGE_BEFORE_RETIREMENT');
 // Primary retires exactly at end. Full working year:100000+1000 contribution, then5% =106050. Younger spouse can retire beyond horizon.
 const p20=base({couple:true,age:40,spouseAge:38,retireAge:41,endAge:41,salary:10000,returnRate:5,accounts:[L.account('r','rothIRA',100000,{contribution:1000,contributionBasis:100000})]});p20.profile.spouseRetireAge=60;
 project('N20','End equals primary retirement and younger spouse still works',p20,[[41,'total',106050]]);
 const monthlyGrid=monthlyOracleGrid();
 // Additional owner-policy hunt, kept separate from the promised 20 cases.
 // Changing current age is not editing the historical retirement date. The stored retirement remains65.
 // At opening70.5, the first half-year pension must be10000*1.1^(70.5-65)*.5=8445.58569033.
 const pH=base({age:70,retireAge:65,endAge:71,pension:10000,accounts:[L.account('r','rothIRA',100000,{contributionBasis:100000})]});pH.retirement.pensionCola=10;
 const hunt={id:'H01',name:'Current-age edit must keep untouched historical retirement date',plan:clone(pH),checks:[]};
 ui=await restore([pH]);try{check(hunt,'retirement initially preserved',ui.saved()[0].profile.retireAge,65);await edit(ui,'v2-age',70.3,q=>q[0].profile.age===70.5);hunt.saved=ui.saved()[0];hunt.shownRetirement=ui.d.getElementById('v2-retire').value;hunt.result=E.runPlan(clone(hunt.saved));check(hunt,'untouched stored retirement',hunt.saved.profile.retireAge,65);check(hunt,'shown retirement',Number(hunt.shownRetirement),65);check(hunt,'pension in half-year',at(hunt.result,71).income,10000*1.1**5.5*.5,.01);const intended=clone(hunt.saved);intended.profile.retireAge=65;hunt.intendedResult=E.runPlan(intended);}finally{ui.w.close();}
 let sourceSha='unavailable';try{sourceSha=cp.execFileSync('git',['-c','core.commitGraph=false','rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8',windowsHide:true}).trim();}catch{}
 const summary={cases:cases.length,checks:cases.reduce((n,c)=>n+c.checks.length,0),passed:cases.filter(c=>c.checks.every(x=>x.pass)).length,failed:cases.filter(c=>c.checks.some(x=>!x.pass)).map(c=>({id:c.id,checks:c.checks.filter(x=>!x.pass)}))};
 fs.writeFileSync(OUT,JSON.stringify({sourceSha,summary,cases,monthlyGrid,hunt},null,2));console.log(JSON.stringify({summary,monthlyGrid:{cases:monthlyGrid.cases,financialChecks:monthlyGrid.financialChecks,failed:monthlyGrid.failed},hunt:hunt.checks},null,2));process.exitCode=summary.failed.length||monthlyGrid.failed||hunt.checks.some(x=>!x.pass)?1:0;
})().catch(e=>{console.error(e.stack);process.exitCode=2;});
